/** Bilingual acceptance and rework directions shared by reading, viewer and PDF. */
export const ORIENTATION_STANDARDS: Record<string, { right: string; rightEs: string; wrong: string; wrongEs: string }> = {
  ARRIVAL: { right:"Introduce yourself, show identification, confirm service and access, and protect floors.", rightEs:"Preséntate, muestra tu credencial, confirma el servicio y las instrucciones de acceso, y protege los pisos.", wrong:"Do not enter unannounced or skip identification, access confirmation or floor protection.", wrongEs:"No entres sin anunciarte. Muestra tu credencial, confirma el acceso y protege los pisos." },
  K1: { right:"Leave counters, sink, faucet bases and reachable edges free of crumbs, residue and standing water.", rightEs:"Deja las encimeras, el fregadero, las bases de las llaves de agua y los bordes accesibles sin migas, residuos ni agua acumulada.", wrong:"Rework crumbs, residue or water left around seams, the sink rim or faucet bases.", wrongEs:"Vuelve a limpiar las migas, los residuos o el agua que queden en las juntas, el borde del fregadero o las bases de las llaves de agua." },
  K2: { right:"Remove grease and splashes from the cooktop and appliance exteriors; leave an even, streak-free finish.", rightEs:"Retira la grasa y las salpicaduras de la estufa y del exterior de los electrodomésticos. Deja un acabado uniforme, sin marcas.", wrong:"Rework greasy patches, fingerprints, spills or streaks on booked exterior surfaces.", wrongEs:"Vuelve a limpiar las zonas con grasa, huellas, derrames o marcas en las superficies exteriores incluidas en el servicio." },
  B1: { right:"Leave shower surfaces and glass free of visible soap film, residue and streaks.", rightEs:"Deja las superficies de la ducha y los vidrios sin residuos de jabón, suciedad ni marcas visibles.", wrong:"Rework soap film and spots, especially at reachable corners, tracks and lower edges.", wrongEs:"Elimina los residuos de jabón y las manchas, sobre todo en las esquinas, los rieles y los bordes inferiores accesibles." },
  B2: { right:"Clean the toilet, sink, faucet and mirror, including reachable bases and edges.", rightEs:"Limpia el inodoro, el lavabo, la llave de agua y el espejo, incluidas las bases y los bordes accesibles.", wrong:"Rework visible residue, splashes or mirror streaks; do not overlook fixture bases.", wrongEs:"Elimina los residuos, las salpicaduras y las marcas del espejo. No olvides las bases de los accesorios del baño." },
  F1: { right:"Remove loose debris from floors and reachable perimeters; leave hard floors without sticky residue.", rightEs:"Retira los residuos sueltos de los pisos y los bordes accesibles. Deja los pisos duros sin residuos pegajosos.", wrong:"Rework debris at edges, missed corners, footprints or sticky patches.", wrongEs:"Vuelve a limpiar los residuos en los bordes, las esquinas sin limpiar, las huellas y las zonas pegajosas." },
  F2: { right:"Dust reachable surfaces and finish booked bed-making and trash removal; keep belongings in place.", rightEs:"Quita el polvo de las superficies accesibles, tiende las camas y retira la basura según lo contratado. Deja las pertenencias en su lugar.", wrong:"Rework visible dust or unfinished presentation; do not rearrange personal belongings.", wrongEs:"Elimina el polvo visible y completa la presentación final. No cambies de lugar las pertenencias del cliente." },
  L1: { right:"Leave a consistent cut across the booked lawn with no visibly missed strips.", rightEs:"Deja un corte uniforme en toda el área de césped contratada, sin franjas sin cortar.", wrong:"Rework uneven patches or missed strips; avoid scalping the lawn.", wrongEs:"Corrige las zonas con cortes desiguales y las franjas sin cortar. Evita cortar el césped demasiado bajo." },
  L2: { right:"Create clear, consistent edges along booked driveways, walks and beds.", rightEs:"Deja bordes definidos y uniformes junto a las entradas para autos, los senderos y los jardines incluidos en el servicio.", wrong:"Rework overgrown or ragged edges and clear clippings from hard surfaces.", wrongEs:"Corrige los bordes con césped crecido o irregular y retira los restos de césped de las superficies pavimentadas." },
  L3: { right:"Trim around fences, posts, trees and A/C pads without damaging bark, fixtures or property.", rightEs:"Recorta alrededor de cercas, postes, árboles y bases de aire acondicionado sin dañar la corteza, las instalaciones ni la propiedad.", wrong:"Do not strike bark or fixtures; report damage and stop any unsafe part of the work.", wrongEs:"No golpees la corteza ni las instalaciones. Informa cualquier daño y detén la parte del trabajo que no sea segura." },
  L4: { right:"Clear hard surfaces, remove visible debris and close and latch every gate used.", rightEs:"Limpia las superficies pavimentadas, retira los residuos visibles y cierra y asegura todos los portones que uses.", wrong:"Rework leftover clippings or debris; never leave an accessed gate open or unlatched.", wrongEs:"Retira los restos de césped y los residuos. Nunca dejes abierto o sin asegurar un portón que hayas usado." },
  C1: { right:"Clean wheels and tires, including reachable spokes and edges, with an even finish.", rightEs:"Limpia las ruedas y los neumáticos, incluidos los radios y los bordes accesibles. Deja un acabado uniforme.", wrong:"Rework visible brake dust, dirt around spokes or uneven tire residue.", wrongEs:"Elimina el polvo de frenos visible, la suciedad entre los radios y los residuos que dejen un acabado desigual en los neumáticos." },
  C2: { right:"Hand-dry the washed exterior and leave booked glass free of visible water spots and streaks.", rightEs:"Seca a mano el exterior lavado. Deja los vidrios incluidos en el servicio sin manchas de agua ni marcas visibles.", wrong:"Rework water spots, dripping edges or streaky glass before closing the visit.", wrongEs:"Elimina las manchas de agua y las marcas de los vidrios. Seca los bordes que goteen antes de finalizar la visita." },
  C3: { right:"Vacuum booked carpets and seats, including safely reachable seams and beneath movable mats.", rightEs:"Aspira las alfombras y los asientos incluidos en el servicio, las costuras accesibles sin riesgo y el área debajo de los tapetes que se puedan retirar.", wrong:"Rework crumbs and debris; do not force seat mechanisms or move items unsafely.", wrongEs:"Retira las migas y los residuos. No fuerces los mecanismos de los asientos ni muevas objetos si no puedes hacerlo sin riesgo." },
  C4: { right:"Wipe booked dashboard, console and reachable vents to a clean, even, non-greasy finish.", rightEs:"Limpia el tablero, la consola y las rejillas de ventilación accesibles incluidos en el servicio. Deja un acabado uniforme, sin grasa.", wrong:"Rework dust, smears or greasy residue; do not leave product pooling around controls.", wrongEs:"Elimina el polvo, las manchas y la grasa. No dejes producto acumulado alrededor de los controles." },
};