export const ORIENTATION_SECTIONS = [
  { id: "before-you-work", title: "Before you work", es: "Antes de trabajar", min: 3, unlock: "Agreement signed", unlockEs: "Acuerdo firmado" },
  { id: "what-it-pays", title: "What it pays", es: "Pagos e ingresos", min: 5, unlock: "Background check started", unlockEs: "Verificación de antecedentes iniciada" },
  { id: "on-the-job", title: "On the job", es: "Durante el servicio", min: 5, unlock: "Background check started", unlockEs: "Verificación de antecedentes iniciada" },
  { id: "when-it-matters", title: "When it matters", es: "Situaciones importantes", min: 6, unlock: "Insurance confirmed", unlockEs: "Seguro confirmado" },
] as const;
export type OrientationSectionId = typeof ORIENTATION_SECTIONS[number]["id"];
export const stageNumber = (stage: string) => ["applied","screened","agreement","ins_quote","background","insured","active"].indexOf(stage) + 1;

export type OrientationBlock = { title: string; esTitle: string; body: string; es: string; image?: string; pair?: string };
export const ORIENTATION_COPY: Record<OrientationSectionId, OrientationBlock[]> = {
  "before-you-work": [
    { title:"Welcome to TIDY", esTitle:"Te damos la bienvenida a TIDY", body:"Your reputation starts at the doorstep. One home. One trusted Pro. One consistent standard.", es:"Tu reputación comienza en la puerta del cliente. Un hogar. Un Pro de confianza. El mismo nivel de calidad en cada visita.", image:"PRO-1" },
    { title:"Our standard", esTitle:"Nuestro estándar", body:"Reliable: arrive within the confirmed window and communicate changes early. Respectful: protect the home, family, privacy, pets and belongings. Thorough: complete the booked services and inspect the details before leaving.", es:"Confiable: llega dentro del horario confirmado y avisa con anticipación si hay cambios. Respetuoso: cuida el hogar, la familia, la privacidad, las mascotas y las pertenencias del cliente. Minucioso: completa los servicios contratados y revisa los detalles antes de irte." },
    { title:"Independent contractor relationship", esTitle:"Tu relación como contratista independiente", body:"TIDY connects customers with qualified Pros and communicates the booked services, arrival window, support channels and payment terms. You choose whether to accept offered work, maintain the required insurance, apply your professional expertise and deliver the agreed result.", es:"TIDY conecta a los clientes con Pros calificados y comunica los servicios contratados, el horario de llegada, los canales de atención al cliente y las condiciones de pago. Tú decides si aceptas el trabajo ofrecido, mantienes el seguro requerido, aplicas tu experiencia profesional y entregas el resultado acordado." },
    { title:"Five readiness gates", esTitle:"Cinco requisitos antes de comenzar", body:"Signed agreement and W-9. Active insurance that meets the requirements. Background screening completed. Optional TIDY kit and identification arranged. Accepted jobs, addresses and access instructions confirmed.", es:"Acuerdo y formulario W-9 firmados. Seguro vigente que cumple con los requisitos. Verificación de antecedentes completada. Kit e identificación TIDY opcionales coordinados. Trabajos aceptados, direcciones e instrucciones de acceso confirmados." },
    { title:"Insurance", esTitle:"Seguro", body:"General liability limits are $1,000,000 per occurrence and $2,000,000 aggregate, with Tidy Home Concierge LLC listed as Additional Insured. Submit the certificate and endorsement through the onboarding channel. Do not begin a paid visit before coverage is confirmed.", es:"El seguro de responsabilidad civil debe cubrir $1,000,000 por incidente y $2,000,000 como límite total de la póliza, e incluir a Tidy Home Concierge LLC como asegurado adicional. Envía el certificado y el endoso del seguro por el canal indicado durante tu incorporación. No comiences una visita remunerada hasta que se confirme la cobertura." },
    { title:"Insurance wording", esTitle:"Cómo solicitar el seguro", body:"Ask your insurer: “Please quote general liability insurance with limits of $1,000,000 per occurrence and $2,000,000 aggregate, and advise whether Tidy Home Concierge LLC can be listed as Additional Insured.”", es:"Pídele a tu aseguradora: “Por favor, envíeme una cotización de seguro de responsabilidad civil con cobertura de $1,000,000 por incidente y $2,000,000 como límite total de la póliza. Indíqueme también si se puede incluir a Tidy Home Concierge LLC como asegurado adicional”." },
    { title:"Screening and privacy", esTitle:"Verificación de antecedentes y privacidad", body:"Customer names, entry codes, photographs, schedules and addresses are confidential. Share them only through approved job channels. Never claim screening or insurance is current unless your status is confirmed.", es:"Los nombres, códigos de acceso, fotografías, horarios y direcciones de los clientes son confidenciales. Comparte esta información únicamente por los canales autorizados para el trabajo. No afirmes que tu verificación de antecedentes está aprobada ni que tu seguro está vigente si TIDY no ha confirmado tu estado." },
    { title:"Your kit", esTitle:"Tu kit de trabajo", body:"TIDY offers a navy polo for cleaning, a navy tee and high-visibility vest for lawn care, and a navy tee for car care. The kit supports clear customer identification.", es:"TIDY ofrece una camisa polo azul marino para limpieza del hogar, una camiseta azul marino y un chaleco de alta visibilidad para cuidado del césped, y una camiseta azul marino para cuidado del auto. El kit permite que el cliente te identifique.", image:"PRO-5" },
    { title:"Your badge", esTitle:"Tu credencial", body:"Keep your TIDY identification available at the door so the customer knows who arrived.", es:"Ten tu credencial TIDY a mano al llegar a la puerta para que el cliente sepa quién eres.", image:"PRO-6" },
    { title:"Your territory", esTitle:"Tu zona de servicio", body:"Launch neighborhoods: Pinecrest 33156, Kendall 33183 and Kendall West 33186. Read every accepted job card for the exact address, scope and access notes.", es:"Zonas de lanzamiento: Pinecrest 33156, Kendall 33183 y Kendall West 33186. Revisa los detalles de cada trabajo que aceptes para confirmar la dirección exacta, los servicios contratados y las instrucciones de acceso." },
  ],
  "what-it-pays": [
    { title:"Pay per completed visit", esTitle:"Pago por visita completada", body:"Cleaning: $56 for up to 2 bedrooms, $76 for 3 bedrooms, $112 for 4 bedrooms. Lawn care: $18 for small, $26 for standard, $40 for large. Car wash: $16 for a sedan, $20 for an SUV, $26 for a truck. Full detail: $78, $88 or $115.", es:"Limpieza del hogar: $56 para viviendas de hasta 2 dormitorios, $76 para 3 dormitorios y $112 para 4 dormitorios. Cuidado del césped: $18 para tamaño pequeño, $26 para estándar y $40 para grande. Lavado de auto: $16 para sedán, $20 para SUV y $26 para camioneta. Limpieza completa del auto: $78, $88 o $115." },
    { title:"Additional earnings", esTitle:"Ingresos adicionales", body:"Authorized and completed add-ons pay 40% of the customer price. A qualifying five-star review that names you earns a $25 bonus once per served member. Tier requirements and their current conditions appear in your Pro portal.", es:"Por los servicios adicionales autorizados y completados, recibes el 40% del precio que paga el cliente. Una reseña válida de cinco estrellas que te mencione por nombre genera un bono de $25, una sola vez por miembro atendido. Los requisitos de cada nivel y sus condiciones vigentes aparecen en tu portal Pro." },
  ],
  "on-the-job": [
    { title:"The visit", esTitle:"La visita", body:"Before: review the accepted job card, exact scope, approved add-ons, access notes, pets, parking and arrival window. On site: identify yourself, protect property and complete the agreed scope. After: inspect, capture the requested photos, close the visit and report exceptions.", es:"Antes: revisa los detalles del trabajo aceptado, los servicios contratados, los adicionales autorizados, las instrucciones de acceso, las mascotas, el estacionamiento y el horario de llegada. Durante: identifícate, cuida la propiedad y completa los servicios acordados. Después: revisa el resultado, toma las fotos solicitadas, marca la visita como finalizada e informa cualquier incidencia." },
    { title:"At the door", esTitle:"Al llegar a la puerta", body:"Introduce yourself, verify the address and booked service, protect floors and confirm access instructions.", es:"Preséntate, verifica la dirección y el servicio contratado, protege los pisos y confirma las instrucciones de acceso.", pair:"ARRIVAL" },
    { title:"Cleaning scope", esTitle:"Servicios de limpieza incluidos", body:"Kitchen: counters, sink, stovetop, appliance exteriors and floors. Bathroom: toilet, shower or tub, sink, mirrors and floors. Every room: reachable dusting, vacuuming, hard floors, bed-making and trash removal as booked.", es:"Cocina: encimeras, fregadero, superficie de la estufa, exteriores de los electrodomésticos y pisos. Baño: inodoro, ducha o bañera, lavabo, espejos y pisos. En cada habitación: quitar el polvo de superficies accesibles, aspirar, limpiar pisos duros, tender las camas y retirar la basura, según lo contratado.", image:"PRO-4" },
    { title:"Kitchen: counters and sink", esTitle:"Cocina: encimeras y fregadero", body:"The difference is in the edges.", es:"Los bordes también deben quedar limpios.", pair:"K1" },
    { title:"Kitchen: cooktop and appliances", esTitle:"Cocina: estufa y electrodomésticos", body:"Leave surfaces clean and streak-free.", es:"Deja las superficies limpias y sin marcas.", pair:"K2" },
    { title:"Bathroom: shower and glass", esTitle:"Baño: ducha y vidrios", body:"Look where soap film hides.", es:"Revisa las zonas donde se acumulan residuos de jabón.", pair:"B1" },
    { title:"Bathroom: toilet, sink and mirror", esTitle:"Baño: inodoro, lavabo y espejo", body:"Clean the details customers inspect.", es:"Limpia los detalles que el cliente revisa.", pair:"B2" },
    { title:"Floors and edges", esTitle:"Pisos y bordes", body:"Edges and corners count, too.", es:"Los bordes y las esquinas también cuentan.", pair:"F1" },
    { title:"Dusting and final presentation", esTitle:"Limpieza del polvo y presentación final", body:"Leave the home clean without rearranging personal belongings.", es:"Deja el hogar limpio, sin cambiar de lugar las pertenencias del cliente.", pair:"F2" },
    { title:"Cleaning add-ons", esTitle:"Servicios adicionales de limpieza", body:"Do not expand the booked scope without authorization. Direct extra requests to the booking channel before proceeding.", es:"No realices servicios que no estén contratados sin autorización. Pide al cliente que solicite los servicios adicionales por el canal de reservas antes de realizarlos." },
    { title:"Lawn scope", esTitle:"Servicios de césped incluidos", body:"Mow to a consistent height; edge driveways, walks and beds; trim around fences, posts, trees and A/C pads; clear hard surfaces; remove visible debris; close and latch every gate used. Measure square feet of turf only, excluding the house, driveway, walkways, patio, pool and decking. Small: up to 3,000; Standard: over 3,000 to 7,000; Large: over 7,000 to 12,000. Larger than the job card states when you arrive? Do not leave the work half-finished or absorb the extra cost: call TIDY.", es:"Corta el césped a una altura uniforme; define los bordes de entradas para autos, senderos y jardines; recorta alrededor de cercas, postes, árboles y bases de aire acondicionado; limpia las superficies pavimentadas; retira los residuos visibles; cierra y asegura los portones que uses. El tamaño se mide en pies cuadrados de césped únicamente: no incluye la casa, la entrada para autos, los senderos, el patio, la piscina ni las terrazas. Pequeño: hasta 3,000; estándar: más de 3,000 y hasta 7,000; grande: más de 7,000 y hasta 12,000. ¿El área es mayor que la indicada en el trabajo al llegar? No dejes el trabajo a medias ni asumas el costo adicional: llama a TIDY.", image:"PRO-2" },
    { title:"The cut", esTitle:"El corte", body:"Consistency is visible from the street.", es:"Un corte uniforme se nota desde la calle.", pair:"L1" },
    { title:"The edge", esTitle:"Los bordes", body:"Precision is part of the result.", es:"La precisión es parte del resultado.", pair:"L2" },
    { title:"Trim without damage", esTitle:"Recorta sin causar daños", body:"Accuracy over speed.", es:"Prioriza la precisión, no la velocidad.", pair:"L3" },
    { title:"Finish the entire property", esTitle:"Completa el trabajo en toda la propiedad", body:"The gate is part of the job.", es:"Cerrar el portón también es parte del trabajo.", pair:"L4" },
    { title:"Car care scope", esTitle:"Servicios de cuidado del auto incluidos", body:"Maintenance wash: exterior wash and hand dry, wheels, tires, door jambs, glass, basic interior vacuum, dashboard and console wipe. Full detail adds deeper attention to seats, carpets, interior plastics and trim as booked.", es:"Lavado de mantenimiento: lavado exterior y secado a mano, limpieza de ruedas, neumáticos, marcos de las puertas y vidrios, aspirado básico del interior y limpieza del tablero y la consola. La limpieza completa del auto incluye una limpieza más profunda de asientos, alfombras, plásticos interiores y molduras, según lo contratado.", image:"PRO-3" },
    { title:"Wheels and tires", esTitle:"Ruedas y neumáticos", body:"Clean the whole wheel, not just its front face.", es:"Limpia toda la rueda, no solo la parte frontal.", pair:"C1" },
    { title:"Paint and glass", esTitle:"Pintura y vidrios", body:"Water spots are unfinished work.", es:"Si quedan manchas de agua, el trabajo no está terminado.", pair:"C2" },
    { title:"Carpets and seats", esTitle:"Alfombras y asientos", body:"Move what can safely be moved.", es:"Mueve solo lo que puedas mover sin riesgo.", pair:"C3" },
    { title:"Dashboard, console and vents", esTitle:"Tablero, consola y rejillas de ventilación", body:"Clean surfaces should not feel greasy.", es:"Las superficies limpias no deben quedar grasosas.", pair:"C4" },
  ],
  "when-it-matters": [
    { title:"Your photo record", esTitle:"Tu registro fotográfico", body:"Capture only the photos requested by the job card and authorized by the customer. Show the completed result without exposing people, personal documents, house numbers, license plates or security details.", es:"Toma únicamente las fotos solicitadas en los detalles del trabajo y autorizadas por el cliente. Muestra el resultado final sin incluir personas, documentos personales, números de vivienda, placas de vehículos ni información de seguridad." },
    { title:"Escalation", esTitle:"Cuándo contactar a TIDY", body:"If access is unsafe, damage is found, scope is unclear or the result cannot be completed as booked, stop that part of the work, document the issue and contact TIDY support promptly.", es:"Si el acceso no es seguro, encuentras daños, los servicios contratados no están claros o no puedes completar el resultado acordado, detén esa parte del trabajo, documenta el problema y contacta cuanto antes al equipo de atención de TIDY." },
    { title:"The 48-hour standard", esTitle:"El plazo de 48 horas", body:"A member has 48 hours after a completed visit to report a service issue. Clear photos and notes help TIDY review what happened and arrange the right next step.", es:"El miembro tiene 48 horas después de una visita completada para informar un problema con el servicio. Las fotos y notas claras ayudan a TIDY a revisar lo ocurrido y coordinar la solución correspondiente." },
    { title:"Boundaries", esTitle:"Límites del servicio", body:"Complete only the accepted services and authorized extras. Protect private information. Do not accept off-platform cash work during a TIDY visit. Leave unsafe areas untouched and report the risk.", es:"Realiza únicamente los servicios aceptados y los adicionales autorizados. Protege la información privada. No aceptes trabajos por fuera de TIDY pagados en efectivo durante una visita de TIDY. No trabajes en una zona insegura e informa el riesgo." },
    { title:"Communication", esTitle:"Comunicación", body:"Use the Pro portal and approved support channels for job updates. Communicate delays early. Keep messages brief, factual and respectful.", es:"Usa el portal Pro y los canales de atención autorizados para informar sobre el trabajo. Avisa con anticipación si te retrasas. Escribe mensajes breves, claros y respetuosos, basados en los hechos." },
    { title:"Scenario: no access", esTitle:"Caso: no puedes entrar", body:"Stay outside, check the job card once, contact the member through the approved channel and notify TIDY. Do not try another entrance without written instructions.", es:"Permanece afuera, revisa los detalles del trabajo una vez, contacta al miembro por el canal autorizado y avisa a TIDY. No intentes entrar por otro lugar sin instrucciones por escrito." },
    { title:"Scenario: extra request", esTitle:"Caso: solicitud adicional", body:"Acknowledge the request and ask the member to add it through TIDY. Begin only after it appears as authorized on the job.", es:"Confirma que recibiste la solicitud y pide al miembro que la agregue a través de TIDY. Realiza el servicio únicamente cuando figure como autorizado en los detalles del trabajo." },
    { title:"Scenario: damage or safety concern", esTitle:"Caso: daños o riesgo de seguridad", body:"Do not hide the issue or keep working near the hazard. Photograph only what is needed, protect the area and contact TIDY support immediately.", es:"No ocultes el problema ni sigas trabajando cerca del riesgo. Fotografía únicamente lo necesario, protege la zona y contacta de inmediato al equipo de atención de TIDY." },
    { title:"Your first assignment", esTitle:"Tu primer trabajo", body:"Confirm the service, date, arrival window, address, access instructions and booked scope in your Pro portal. Accept only work you can complete to the stated result.", es:"Confirma en tu portal Pro el servicio, la fecha, el horario de llegada, la dirección, las instrucciones de acceso y los servicios contratados. Acepta únicamente los trabajos que puedas completar con el resultado acordado." },
  ],
};
