/** Supplemental result directions; the approved source copy remains unchanged. */
export const ORIENTATION_STANDARDS: Record<string, { right: string; rightEs: string; wrong: string; wrongEs: string }> = {
  ARRIVAL: { right:"Introduce yourself, show identification, confirm service and access, and protect floors.", rightEs:"Preséntate, muestra identificación, confirma servicio y acceso y protege los pisos.", wrong:"Do not enter unannounced or skip identification, access confirmation or floor protection.", wrongEs:"No entres sin anunciarte ni omitas identificación, confirmación de acceso o protección de pisos." },
  K1: { right:"Leave counters, sink, faucet bases and reachable edges free of crumbs, residue and standing water.", rightEs:"Deja mostradores, fregadero, bases de grifos y bordes accesibles sin migas, residuos ni agua acumulada.", wrong:"Rework crumbs, residue or water left around seams, the sink rim or faucet bases.", wrongEs:"Corrige migas, residuos o agua en uniones, bordes del fregadero o bases de grifos." },
  K2: { right:"Remove grease and splashes from the cooktop and appliance exteriors; leave an even, streak-free finish.", rightEs:"Retira grasa y salpicaduras de la estufa y exteriores; deja un acabado uniforme sin marcas.", wrong:"Rework greasy patches, fingerprints, spills or streaks on booked exterior surfaces.", wrongEs:"Corrige grasa, huellas, derrames o marcas en los exteriores reservados." },
  B1: { right:"Leave shower surfaces and glass free of visible soap film, residue and streaks.", rightEs:"Deja superficies de ducha y vidrio sin película de jabón, residuos ni marcas visibles.", wrong:"Rework soap film and spots, especially at reachable corners, tracks and lower edges.", wrongEs:"Corrige jabón y manchas, especialmente en esquinas, rieles y bordes inferiores accesibles." },
  B2: { right:"Clean the toilet, sink, faucet and mirror, including reachable bases and edges.", rightEs:"Limpia inodoro, lavabo, grifo y espejo, incluidas bases y bordes accesibles.", wrong:"Rework visible residue, splashes or mirror streaks; do not overlook fixture bases.", wrongEs:"Corrige residuos, salpicaduras o marcas del espejo; no omitas las bases." },
  F1: { right:"Remove loose debris from floors and reachable perimeters; leave hard floors without sticky residue.", rightEs:"Retira residuos sueltos de pisos y perímetros accesibles; deja pisos duros sin residuos pegajosos.", wrong:"Rework debris at edges, missed corners, footprints or sticky patches.", wrongEs:"Corrige residuos en bordes, esquinas omitidas, huellas o zonas pegajosas." },
  F2: { right:"Dust reachable surfaces and finish booked bed-making and trash removal; keep belongings in place.", rightEs:"Quita polvo accesible y termina cama y basura reservadas; conserva los objetos en su lugar.", wrong:"Rework visible dust or unfinished presentation; do not rearrange personal belongings.", wrongEs:"Corrige polvo visible o presentación incompleta; no reorganices objetos personales." },
  L1: { right:"Leave a consistent cut across the booked lawn with no visibly missed strips.", rightEs:"Deja un corte uniforme en el césped reservado sin franjas visiblemente omitidas.", wrong:"Rework uneven patches or missed strips; avoid scalping the lawn.", wrongEs:"Corrige zonas desiguales o franjas omitidas; evita cortar demasiado bajo." },
  L2: { right:"Create clear, consistent edges along booked driveways, walks and beds.", rightEs:"Perfila bordes definidos y uniformes en entradas, caminos y canteros reservados.", wrong:"Rework overgrown or ragged edges and clear clippings from hard surfaces.", wrongEs:"Corrige bordes crecidos o irregulares y retira recortes de superficies duras." },
  L3: { right:"Trim around fences, posts, trees and A/C pads without damaging bark, fixtures or property.", rightEs:"Recorta alrededor de cercas, postes, árboles y equipos sin dañar corteza, instalaciones o propiedad.", wrong:"Do not strike bark or fixtures; report damage and stop any unsafe part of the work.", wrongEs:"No golpees corteza o instalaciones; reporta daños y detén cualquier parte insegura." },
  L4: { right:"Clear hard surfaces, remove visible debris and close and latch every gate used.", rightEs:"Despeja superficies duras, retira residuos visibles y cierra y asegura cada portón usado.", wrong:"Rework leftover clippings or debris; never leave an accessed gate open or unlatched.", wrongEs:"Corrige recortes o residuos restantes; nunca dejes un portón abierto o sin asegurar." },
  C1: { right:"Clean wheels and tires, including reachable spokes and edges, with an even finish.", rightEs:"Limpia ruedas y neumáticos, incluidos radios y bordes accesibles, con acabado uniforme.", wrong:"Rework visible brake dust, dirt around spokes or uneven tire residue.", wrongEs:"Corrige polvo de frenos visible, suciedad en radios o residuos desiguales en neumáticos." },
  C2: { right:"Hand-dry the washed exterior and leave booked glass free of visible water spots and streaks.", rightEs:"Seca a mano el exterior lavado y deja vidrios reservados sin manchas de agua ni marcas visibles.", wrong:"Rework water spots, dripping edges or streaky glass before closing the visit.", wrongEs:"Corrige manchas de agua, bordes que gotean o vidrio marcado antes de cerrar la visita." },
  C3: { right:"Vacuum booked carpets and seats, including safely reachable seams and beneath movable mats.", rightEs:"Aspira alfombras y asientos reservados, incluidas uniones seguras y debajo de tapetes movibles.", wrong:"Rework crumbs and debris; do not force seat mechanisms or move items unsafely.", wrongEs:"Corrige migas y residuos; no fuerces mecanismos de asientos ni muevas objetos sin seguridad." },
  C4: { right:"Wipe booked dashboard, console and reachable vents to a clean, even, non-greasy finish.", rightEs:"Limpia tablero, consola y ventilas accesibles reservados con acabado uniforme y sin grasa.", wrong:"Rework dust, smears or greasy residue; do not leave product pooling around controls.", wrongEs:"Corrige polvo, manchas o grasa; no dejes producto acumulado alrededor de controles." },
};