export const ORIENTATION_SECTIONS = [
  { id: "before-you-work", title: "Before you work", es: "Antes de trabajar", min: 3, unlock: "Agreement signed", unlockEs: "Acuerdo firmado" },
  { id: "what-it-pays", title: "What it pays", es: "Lo que paga", min: 5, unlock: "Background check started", unlockEs: "Verificación de antecedentes iniciada" },
  { id: "on-the-job", title: "On the job", es: "Durante el servicio", min: 5, unlock: "Background check started", unlockEs: "Verificación de antecedentes iniciada" },
  { id: "when-it-matters", title: "When it matters", es: "Cuando importa", min: 6, unlock: "Insurance confirmed", unlockEs: "Seguro confirmado" },
] as const;
export type OrientationSectionId = typeof ORIENTATION_SECTIONS[number]["id"];
export const stageNumber = (stage: string) => ["applied","screened","agreement","ins_quote","background","insured","active"].indexOf(stage) + 1;

export type OrientationBlock = { title: string; esTitle: string; body: string; es: string; image?: string; pair?: string };
export const ORIENTATION_COPY: Record<OrientationSectionId, OrientationBlock[]> = {
  "before-you-work": [
    { title:"Welcome to TIDY", esTitle:"Bienvenido a TIDY", body:"Your reputation starts at the doorstep. One home. One trusted Pro. One consistent standard.", es:"Tu reputación comienza en la puerta. Un hogar. Un Pro de confianza. Un estándar constante.", image:"PRO-1" },
    { title:"Our standard", esTitle:"Nuestro estándar", body:"Reliable: arrive in the confirmed window and communicate changes early. Respectful: protect the home, family, privacy, pets and property. Thorough: complete the booked scope and inspect the details before leaving.", es:"Confiable: llega dentro del horario confirmado y comunica los cambios con anticipación. Respetuoso: protege el hogar, la familia, la privacidad, las mascotas y la propiedad. Minucioso: completa el alcance reservado y revisa los detalles antes de salir." },
    { title:"Independent contractor relationship", esTitle:"Relación de contratista independiente", body:"TIDY connects customers with qualified Pros and communicates the booked scope, arrival window, customer support and payment terms. You choose whether to accept offered work, maintain qualifying coverage, use your professional expertise and deliver the agreed result.", es:"TIDY conecta a los clientes con Pros calificados y comunica el alcance reservado, la ventana de llegada, el apoyo al cliente y los términos de pago. Tú eliges si aceptas el trabajo ofrecido, mantienes la cobertura correspondiente, usas tu experiencia profesional y entregas el resultado acordado." },
    { title:"Five readiness gates", esTitle:"Cinco pasos de preparación", body:"Signed agreement and W-9. Active qualifying insurance. Background screening complete. Optional TIDY kit and identification arranged. Accepted assignments, locations and access instructions confirmed.", es:"Acuerdo y W-9 firmados. Seguro calificado activo. Revisión de antecedentes completada. Kit TIDY e identificación opcionales coordinados. Asignaciones aceptadas, ubicaciones e instrucciones de acceso confirmadas." },
    { title:"Insurance", esTitle:"Seguro", body:"General liability limits are $1,000,000 per occurrence and $2,000,000 aggregate, with Tidy Home Concierge LLC listed as Additional Insured. Submit the certificate and endorsement through the onboarding channel. Do not begin a paid visit before coverage is confirmed.", es:"Los límites de responsabilidad civil son $1,000,000 por incidente y $2,000,000 en total, con Tidy Home Concierge LLC como Asegurado Adicional. Envía el certificado y el endoso por el canal de incorporación. No comiences una visita pagada antes de confirmar la cobertura." },
    { title:"Insurance wording", esTitle:"Texto para el seguro", body:"Ask your insurer: “Please quote general liability insurance with limits of $1,000,000 per occurrence and $2,000,000 aggregate, and advise whether Tidy Home Concierge LLC can be listed as Additional Insured.”", es:"Pide a tu aseguradora: “Por favor cotice un seguro de responsabilidad civil con límites de $1,000,000 por incidente y $2,000,000 en total, e indique si Tidy Home Concierge LLC puede figurar como Asegurado Adicional.”" },
    { title:"Screening and privacy", esTitle:"Revisión y privacidad", body:"Customer names, entry codes, photographs, schedules and addresses are confidential. Share them only through approved job channels. Never claim screening or insurance is current unless your status is confirmed.", es:"Los nombres, códigos de entrada, fotos, horarios y direcciones de clientes son confidenciales. Compártelos solo por los canales aprobados del trabajo. Nunca afirmes que tu revisión o seguro está vigente sin confirmación." },
    { title:"Your kit", esTitle:"Tu kit", body:"TIDY offers a navy polo for cleaning, a navy tee and high-visibility vest for lawn care, and a navy tee for car care. The kit supports clear customer identification.", es:"TIDY ofrece un polo azul marino para limpieza, una camiseta azul marino y chaleco de alta visibilidad para césped, y una camiseta azul marino para cuidado del auto. El kit ayuda a que el cliente te identifique.", image:"PRO-5" },
    { title:"Your badge", esTitle:"Tu identificación", body:"Keep your TIDY identification available at the door so the customer knows who arrived.", es:"Ten tu identificación TIDY disponible en la puerta para que el cliente sepa quién llegó.", image:"PRO-6" },
    { title:"Your territory", esTitle:"Tu territorio", body:"Launch neighborhoods: Pinecrest 33156, Kendall 33183 and Kendall West 33186. Read every accepted job card for the exact address, scope and access notes.", es:"Vecindarios iniciales: Pinecrest 33156, Kendall 33183 y Kendall West 33186. Lee cada tarjeta de trabajo aceptada para ver la dirección exacta, el alcance y las notas de acceso." },
  ],
  "what-it-pays": [
    { title:"Pay per completed visit", esTitle:"Pago por visita completada", body:"Cleaning: $56 up to 2 bedrooms, $76 for 3 bedrooms, $112 for 4 bedrooms. Lawn: $18 small yard, $26 standard yard, $40 large yard. Car wash: $16 sedan, $20 SUV, $26 truck. Full detail: $78, $88 or $115.", es:"Limpieza: $56 hasta 2 habitaciones, $76 para 3, $112 para 4. Césped: $18 patio pequeño, $26 estándar, $40 grande. Lavado: $16 sedán, $20 SUV, $26 camioneta. Detalle completo: $78, $88 o $115." },
    { title:"Additional earnings", esTitle:"Ganancias adicionales", body:"Authorized and completed add-ons pay 40% of the customer price. A qualifying named five-star review pays $25 once per served member. Tier milestones and their current conditions appear in your Pro portal.", es:"Los servicios adicionales autorizados y completados pagan el 40% del precio al cliente. Una reseña calificada de cinco estrellas con nombre paga $25 una vez por miembro atendido. Los niveles y sus condiciones actuales aparecen en tu portal Pro." },
  ],
  "on-the-job": [
    { title:"The visit", esTitle:"La visita", body:"Before: review the accepted job card, exact scope, approved add-ons, access notes, pets, parking and arrival window. On site: identify yourself, protect property and complete the agreed scope. After: inspect, capture the requested photos, close the visit and report exceptions.", es:"Antes: revisa la tarjeta aceptada, el alcance exacto, extras aprobados, acceso, mascotas, estacionamiento y llegada. En el lugar: identifícate, protege la propiedad y completa lo acordado. Después: revisa, toma las fotos solicitadas, cierra la visita y reporta excepciones." },
    { title:"At the door", esTitle:"En la puerta", body:"Introduce yourself, verify the address and booked service, protect floors and confirm access instructions.", es:"Preséntate, verifica la dirección y el servicio reservado, protege los pisos y confirma las instrucciones de acceso.", pair:"ARRIVAL" },
    { title:"Cleaning scope", esTitle:"Alcance de limpieza", body:"Kitchen: counters, sink, stovetop, appliance exteriors and floors. Bathroom: toilet, shower or tub, sink, mirrors and floors. Every room: reachable dusting, vacuuming, hard floors, bed-making and trash removal as booked.", es:"Cocina: mostradores, fregadero, estufa, exteriores de electrodomésticos y pisos. Baño: inodoro, ducha o bañera, lavabo, espejos y pisos. Cada habitación: polvo accesible, aspirado, pisos, cama y basura según la reserva.", image:"PRO-4" },
    { title:"Kitchen: counters and sink", esTitle:"Cocina: mostradores y fregadero", body:"The difference is in the edges.", es:"La diferencia está en los bordes.", pair:"K1" },
    { title:"Kitchen: cooktop and appliances", esTitle:"Cocina: estufa y electrodomésticos", body:"A finished surface looks finished.", es:"Una superficie terminada se ve terminada.", pair:"K2" },
    { title:"Bathroom: shower and glass", esTitle:"Baño: ducha y vidrio", body:"Look where soap film hides.", es:"Mira donde se esconde el residuo de jabón.", pair:"B1" },
    { title:"Bathroom: toilet, sink and mirror", esTitle:"Baño: inodoro, lavabo y espejo", body:"Clean the details customers inspect.", es:"Limpia los detalles que el cliente revisa.", pair:"B2" },
    { title:"Floors and edges", esTitle:"Pisos y bordes", body:"The perimeter counts.", es:"El perímetro cuenta.", pair:"F1" },
    { title:"Dusting and final presentation", esTitle:"Polvo y presentación final", body:"Leave the home better, not rearranged.", es:"Deja el hogar mejor, no reorganizado.", pair:"F2" },
    { title:"Cleaning add-ons", esTitle:"Extras de limpieza", body:"Do not expand the booked scope without authorization. Direct extra requests to the booking channel before proceeding.", es:"No amplíes el alcance reservado sin autorización. Dirige las solicitudes extra al canal de reservas antes de continuar." },
    { title:"Lawn scope", esTitle:"Alcance de césped", body:"Mow to a consistent height; edge driveways, walks and beds; trim around fences, posts, trees and A/C pads; clear hard surfaces; remove visible debris; close and latch any gate used. Sizes are square feet of turf only — never the house, driveway, walkways, patio, pool or decking: Small up to 3,000, Standard 3,000–7,000, Large 7,000–12,000. Bigger than the job card on arrival? Don't cut it short and don't absorb it — call Tidy.", es:"Corta a una altura uniforme; perfila entradas, caminos y canteros; recorta alrededor de cercas, postes, árboles y equipos; despeja superficies duras; retira residuos visibles; cierra y asegura cada portón usado. Los tamaños son pies² de césped solamente — nunca la casa, entrada, caminos, patio, piscina ni deck: Pequeño hasta 3,000, Estándar 3,000–7,000, Grande 7,000–12,000. ¿Más grande que la tarjeta al llegar? No lo cortes a medias ni lo absorbas — llama a Tidy.", image:"PRO-2" },
    { title:"The cut", esTitle:"El corte", body:"Consistency is visible from the street.", es:"La consistencia se ve desde la calle.", pair:"L1" },
    { title:"The edge", esTitle:"El borde", body:"Precision is part of the result.", es:"La precisión es parte del resultado.", pair:"L2" },
    { title:"Trim without damage", esTitle:"Recorta sin daño", body:"Accuracy over speed.", es:"Precisión antes que velocidad.", pair:"L3" },
    { title:"Finish the entire property", esTitle:"Termina toda la propiedad", body:"The gate is part of the job.", es:"El portón es parte del trabajo.", pair:"L4" },
    { title:"Car care scope", esTitle:"Alcance de cuidado del auto", body:"Maintenance wash: exterior wash and hand dry, wheels, tires, door jambs, glass, basic interior vacuum, dashboard and console wipe. Full detail adds deeper attention to seats, carpets, interior plastics and trim as booked.", es:"Lavado de mantenimiento: exterior y secado a mano, ruedas, neumáticos, marcos de puertas, vidrios, aspirado interior básico, tablero y consola. El detalle completo añade atención profunda a asientos, alfombras, plásticos y molduras según la reserva.", image:"PRO-3" },
    { title:"Wheels and tires", esTitle:"Ruedas y neumáticos", body:"The face is not the whole wheel.", es:"La cara no es toda la rueda.", pair:"C1" },
    { title:"Paint and glass", esTitle:"Pintura y vidrio", body:"Water spots are unfinished work.", es:"Las marcas de agua son trabajo sin terminar.", pair:"C2" },
    { title:"Carpets and seats", esTitle:"Alfombras y asientos", body:"Move what can safely be moved.", es:"Mueve lo que se pueda mover con seguridad.", pair:"C3" },
    { title:"Dashboard, console and vents", esTitle:"Tablero, consola y ventilas", body:"Clean should not mean greasy.", es:"Limpio no significa grasoso.", pair:"C4" },
  ],
  "when-it-matters": [
    { title:"Your photo record", esTitle:"Tu registro de fotos", body:"Capture only the photos requested by the job card and authorized by the customer. Show the completed result without exposing people, personal documents, house numbers, license plates or security details.", es:"Toma solo las fotos solicitadas en la tarjeta y autorizadas por el cliente. Muestra el resultado sin exponer personas, documentos, números de casa, placas ni detalles de seguridad." },
    { title:"Escalation", esTitle:"Escalamiento", body:"If access is unsafe, damage is found, scope is unclear or the result cannot be completed as booked, stop that part of the work, document the issue and contact TIDY support promptly.", es:"Si el acceso no es seguro, encuentras daño, el alcance no está claro o el resultado no puede completarse como fue reservado, detén esa parte, documenta el problema y contacta pronto al apoyo de TIDY." },
    { title:"The 48-hour standard", esTitle:"El estándar de 48 horas", body:"A member has 48 hours after a completed visit to report a service issue. Clear photos and notes help TIDY review what happened and arrange the right next step.", es:"Un miembro tiene 48 horas después de una visita completada para reportar un problema. Fotos y notas claras ayudan a TIDY a revisar lo ocurrido y coordinar el siguiente paso." },
    { title:"Boundaries", esTitle:"Límites", body:"Complete only the accepted scope and authorized extras. Protect private information. Do not accept cash side work during a TIDY visit. Leave an unsafe area untouched and report it.", es:"Completa solo el alcance aceptado y los extras autorizados. Protege la información privada. No aceptes trabajo en efectivo durante una visita TIDY. No toques un área insegura y repórtala." },
    { title:"Communication", esTitle:"Comunicación", body:"Use the Pro portal and approved support channels for job updates. Communicate delays early. Keep messages brief, factual and respectful.", es:"Usa el portal Pro y los canales aprobados para actualizaciones. Comunica retrasos con anticipación. Mantén los mensajes breves, objetivos y respetuosos." },
    { title:"Scenario: no access", esTitle:"Escenario: sin acceso", body:"Stay outside, check the job card once, contact the member through the approved channel and notify TIDY. Do not try another entrance without written instructions.", es:"Quédate afuera, revisa la tarjeta una vez, contacta al miembro por el canal aprobado y avisa a TIDY. No intentes otra entrada sin instrucciones escritas." },
    { title:"Scenario: extra request", esTitle:"Escenario: solicitud extra", body:"Acknowledge the request and direct the member to add it through TIDY. Begin it only after it appears as authorized on the job.", es:"Reconoce la solicitud y dirige al miembro a añadirla por TIDY. Comiénzala solo cuando aparezca autorizada en el trabajo." },
    { title:"Scenario: damage or safety concern", esTitle:"Escenario: daño o riesgo", body:"Do not hide it or keep working around it. Photograph only what is needed, protect the area, and contact TIDY support immediately.", es:"No lo ocultes ni sigas trabajando alrededor. Fotografía solo lo necesario, protege el área y contacta a TIDY de inmediato." },
    { title:"Your first assignment", esTitle:"Tu primera asignación", body:"Confirm the service, date, arrival window, address, access instructions and booked scope in your Pro portal. Accept only work you can complete to the stated result.", es:"Confirma servicio, fecha, ventana de llegada, dirección, acceso y alcance reservado en tu portal Pro. Acepta solo trabajo que puedas completar con el resultado indicado." },
  ],
};
