import { ShieldCheck, LockKeyhole, MessageCircle, ArrowUpRight, Check, Clock3, AlertTriangle, MapPin, Camera, Handshake, Heart, ClipboardCheck, Home, Leaf, Car, FileCheck, IdCard, CalendarDays } from "lucide-react";
import TidyLogo from "@/components/TidyLogo";
import { OrientationImages } from "./OrientationContent";
import { orientationSegments, orientationVisual } from "@/lib/orientation-design";
import type { OrientationBlock } from "@/lib/orientation";
import agreementArt from "@/assets/orientation/gates/agreement.png";
import insuranceArt from "@/assets/orientation/gates/insurance.png";
import screeningArt from "@/assets/orientation/gates/screening.png";
import identificationArt from "@/assets/orientation/gates/identification.png";
import assignmentArt from "@/assets/orientation/gates/assignment.png";
import serviceKits from "@/assets/orientation/service-kits-reference.jpg";

export function OrientationComposition({ block, sectionId, index, interactive = true }: { block: OrientationBlock; sectionId: string; index: number; interactive?: boolean }) {
  const v = orientationVisual(block, sectionId, index);
  const en = orientationSegments(block.body), es = orientationSegments(block.es);
  const Copy = () => <div className="orientation-slide-copy"><h1>{block.title}</h1><p>{block.body}</p><div lang="es"><h2>{block.esTitle}</h2><p>{block.es}</p></div></div>;
  const Title = () => <div className="orientation-composition-title"><h1>{block.title}</h1><h2 lang="es">{block.esTitle}</h2></div>;
  const Photo = () => v.image ? <img src={v.image} width={1536} height={1024} alt={block.title} className="orientation-photo" /> : null;
  const ReferencePhotos = () => <div className="orientation-reference-strip">{v.references.map((src,i) => <img key={src} src={src} alt={`${block.title} — ${i+1}`} />)}</div>;
  const Tiles = ({ symbols = false }: { symbols?: boolean }) => <div className="orientation-content-tiles">{en.map((s, i) => <div className="orientation-content-tile" key={s}><span className="orientation-tile-number">{symbols ? <Check /> : String(i + 1).padStart(2, "0")}</span><p>{s}</p>{es[i] && <p lang="es">{es[i]}</p>}</div>)}</div>;
  if (block.pair) return <><Copy /><OrientationImages block={block} eager interactive={interactive} /></>;
  if (v.layout === "opener") return <><div className="orientation-cover-photo"><Photo /></div><div className="orientation-cover-copy"><TidyLogo /><h1>Welcome<br />to <em>TIDY.</em></h1><p>{block.body}</p><div lang="es"><h2>{block.esTitle}</h2><p>{block.es}</p></div><div className="orientation-service-symbols"><Home /><Leaf /><Car /></div></div></>;
  if (v.layout === "badge") return <><Copy /><div className="orientation-badge-stage"><div className="orientation-id-badge"><div className="orientation-id-top"><TidyLogo /><strong>TIDY PRO</strong></div><Photo /><strong className="orientation-id-name">ALEX RIVERA</strong><span className="orientation-id-role">Independent Pro / Pro independiente</span><div className="orientation-id-bottom">SAMPLE / EJEMPLO</div></div></div></>;
  if (v.layout === "kit") return <><Title /><div className="orientation-kit-labels">{[["House Cleaning","Limpieza del hogar"],["Lawn Care","Cuidado del césped"],["Car Care","Cuidado del auto"]].map(([label,spanish])=><div key={label}><strong>{label}</strong><span lang="es">{spanish}</span></div>)}</div><img className="orientation-service-kits" src={serviceKits} width={1920} height={1024} alt="Three service-specific TIDY kits with sample identification and optional car magnets" /><div className="orientation-kit-bottom"><div className="orientation-wide-copy"><p>{block.body}</p><p lang="es">{block.es}</p></div><div className="orientation-kit-detail"><Photo /><ReferencePhotos /></div></div><p className="orientation-kit-note">Car magnets optional. / Imanes para auto opcionales.</p></>;
  if (v.layout === "pillars") return <><Title /><div className="orientation-pillar-grid">{[ShieldCheck,Heart,ClipboardCheck].map((Icon,i) => <div className="orientation-pillar" key={i}><Icon /><h3>{en[i]?.split(":")[0]}</h3><p>{en[i]?.slice(en[i].indexOf(":")+1).trim()}</p><h4 lang="es">{es[i]?.split(":")[0]}</h4><p lang="es">{es[i]?.slice(es[i].indexOf(":")+1).trim()}</p></div>)}</div><ReferencePhotos /></>;
  if (v.layout === "gates") return <><Title /><div className="orientation-gate-grid">{[agreementArt,insuranceArt,screeningArt,identificationArt,assignmentArt].map((src,i) => <div className="orientation-gate" key={src}><span>{String(i+1).padStart(2,"0")}</span><div className="orientation-gate-art"><img src={src} alt="" width={256} height={256} /></div><p>{en[i]}</p><p lang="es">{es[i]}</p></div>)}</div><ReferencePhotos /></>;
  if (v.layout === "timeline") return <><Title /><div className="orientation-visit-steps">{[[MapPin,"Arrive","Llegar"],[ClipboardCheck,"Complete","Completar"],[ShieldCheck,"Inspect","Revisar"],[Camera,"Close out","Finalizar"]].map(([Icon,label,spanish],i)=>{const Symbol=Icon as typeof MapPin;return <div key={String(label)}><span className="orientation-visit-circle"><Symbol /><b>{i+1}</b></span><h3>{String(label)}</h3><p lang="es">{String(spanish)}</p></div>;})}</div><div className="orientation-wide-copy"><p>{block.body}</p><p lang="es">{block.es}</p></div></>;
  if (["pay", "steps"].includes(v.layout)) return <><Title /><Tiles /></>;
  if (v.layout === "relationship") return <><Title /><div className="orientation-relationship-grid">{[[Home,"TIDY",en[0],es[0]],[Handshake,"YOU / TÚ",en[1],es[1]],[Heart,"TOGETHER / JUNTOS","The agreed result.","El resultado acordado."]].map(([Icon,label,english,spanish])=>{const Symbol=Icon as typeof Home;return <div key={String(label)}><Symbol /><h3>{String(label)}</h3><p>{String(english)}</p><p lang="es">{String(spanish)}</p></div>;})}</div><ReferencePhotos /></>;
  if (v.layout === "philosophy") return <><Copy /><div className="orientation-philosophy-photo"><ReferencePhotos /></div></>;
  if (v.layout === "purpose") return <><div className="orientation-purpose-photos"><ReferencePhotos /></div><div className="orientation-purpose-copy"><Title /><div className="orientation-wide-copy"><p>{block.body}</p><p lang="es">{block.es}</p></div></div></>;
  if (v.layout === "territory") return <><Title /><div className="orientation-zip-grid">{[["33156","Pinecrest"],["33183","Kendall"],["33186","Kendall West"]].map(([zip, label]) => <div key={zip}><MapPin /><strong>{zip}</strong><span>{label}</span></div>)}</div><div className="orientation-wide-copy"><p>{block.body}</p><p lang="es">{block.es}</p></div></>;
  if (v.layout === "stat") return <><div className="orientation-stat-callout"><strong>{v.stat}</strong><Clock3 /></div><Copy /></>;
  if (v.layout === "coverage") return <><div className="orientation-insurance-copy"><div className="orientation-insurance-heading"><ShieldCheck /><Title /></div><div className="orientation-coverage-card"><div><ShieldCheck /><p><strong>$1,000,000</strong><span>per occurrence / por incidente</span></p></div><div><ShieldCheck /><p><strong>$2,000,000</strong><span>aggregate / límite total</span></p></div></div><div className="orientation-wide-copy"><p>{block.body}</p><p lang="es">{block.es}</p></div></div><div className="orientation-certificate-stage"><div className="orientation-certificate"><p className="orientation-certificate-sample">SAMPLE / EJEMPLO</p><h3>CERTIFICATE OF LIABILITY INSURANCE</h3><p lang="es">CERTIFICADO DE SEGURO DE RESPONSABILIDAD CIVIL</p><div className="orientation-certificate-rule" /><p>GENERAL LIABILITY / RESPONSABILIDAD CIVIL</p><div className="orientation-certificate-row"><span>PER OCCURRENCE<br />POR INCIDENTE</span><strong>$1,000,000</strong></div><div className="orientation-certificate-row"><span>AGGREGATE<br />LÍMITE TOTAL</span><strong>$2,000,000</strong></div><div className="orientation-certificate-insured"><span>ADDITIONAL INSURED / ASEGURADO ADICIONAL</span><strong>Tidy Home Concierge LLC</strong></div></div><div className="orientation-certificate-source"><ReferencePhotos /></div></div></>;
  if (v.layout === "quote") return <><Copy /><div className="orientation-document-photo"><ReferencePhotos /></div></>;
  if (v.layout === "editorial" && v.references.length) return <><Title /><div className="orientation-editorial-tiles"><div><Handshake /><p>{en[0]}</p><p lang="es">{es[0]}</p></div><div><ShieldCheck /><p>{en[1]}</p><p lang="es">{es[1]}</p></div></div><ReferencePhotos /></>;
  if (v.layout === "privacy") return <><Copy /><div className="orientation-document-photo"><ReferencePhotos /></div></>;
  if (v.layout === "finale") return <><div className="orientation-finale-copy"><TidyLogo /><Copy /><div className="orientation-service-symbols"><Home /><Leaf /><Car /><ShieldCheck /></div></div><div className="orientation-finale-photos"><ReferencePhotos /></div></>;
  if (["privacy", "boundary", "message", "scenario-graphic", "alert", "editorial"].includes(v.layout)) {
    const Icon = v.layout === "privacy" ? LockKeyhole : v.layout === "message" ? MessageCircle : v.layout === "alert" ? AlertTriangle : v.layout === "editorial" ? Handshake : ArrowUpRight;
    return <><div className="orientation-symbol-panel"><Icon strokeWidth={1.5} /><span aria-hidden="true">{String(v.number + 1).padStart(2,"0")}</span></div><Copy /></>;
  }
  return <><Copy /><div className="orientation-story-photo"><Photo />{v.layout === "photo-story" && <Camera className="orientation-photo-symbol" />}{v.layout === "finale" && <Check className="orientation-photo-symbol" />}</div></>;
}